FROM mcr.microsoft.com/mssql/server:2019-latest

USER root

# Instalar sqlcmd y dependencias
RUN apt-get update && \
    apt-get install -y curl gnupg apt-transport-https && \
    curl -sSL https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl -sSL https://packages.microsoft.com/config/ubuntu/20.04/prod.list -o /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev && \
    echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> /etc/bash.bashrc && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copiar scripts
COPY ddl_persona_db.sql /scripts/ddl_persona_db.sql
COPY dml_persona_db.sql /scripts/dml_persona_db.sql
COPY init-db.sh /scripts/init-db.sh

# Dar permisos de ejecución
RUN chmod +x /scripts/init-db.sh

# Volver al usuario por defecto
USER mssql

# Script de inicio
CMD /bin/bash -c "/opt/mssql/bin/sqlservr & /scripts/init-db.sh && tail -f /dev/null"